management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
logging:
  pattern:
    level: '[${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
spring:
  application:
    name: payment-service
  thread-executer: virtual


